---
abstract: 'Inflators to serialize data structures for DBIx::Class'
author:
  - 'Jose Luis Martinez (jlmartinez@capside.com)'
build_requires:
  DBD::SQLite: 0
  JSON: 0
  Test::Exception: 0
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-Serializer
requires:
  DBIx::Class: 0
resources:
  homepage: http://metacpan.org/release/DBIx-Class-InflateColumn-Serializer/
  repository: git://github.com/miquelruiz/DBIx-Class-InflateColumn-Serializer.git
version: 0.05
